version: '3'

services:
  db:
    container_name: mariadb-server
    build: .
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql/
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - virtual-net
volumes: 
  mariadb-data:
networks:
  virtual-net:
