version: '3'
services:
  mongo:
    build: .
    restart: always
    container_name: mongodb-server
    env_file:
    - .env        
    ports:
      - '27017:27017'
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
  mongosetup:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - .:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]