version: '3'

services:
  db:
    container_name: postgres-server
    build: .
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - virtual-net
volumes: 
  pgdata:
networks:
  virtual-net:
